### ISSUE TITLE
Idea: Update `Manifest.toml` files even when there is no change to `[compat]`

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/CompatHelper.jl#111]
Consider this situation. Your `Project.toml` file looks like this:
```toml
[deps]
Foo = "uuid_for_foo_package"

[compat]
Foo = "2"
```

And your `Manifest.toml` file has `Foo` at version `2.0.0`.

Now suppose that `Foo` releases version `2.0.1`.

Your existing compat entry of `Foo = "2"` includes this new release `2.0.1`. So CompatHelper will not make an PR to bump your compat entry for `Foo`. After all, you don't need to bump your compat entry for `Foo`.

But, since you made the decision to check your `Manifest.toml` into source control, perhaps you would like to update your `Manifest.toml` file so that it has `Foo` at version `2.0.1` instead of version `2.0.0`?

I think we should have the option for CompatHelper to make a PR in these cases, so that you can keep your `Manifest.toml` files up-to-date even if your compat entries do not need to be bumped.

As with everything in CompatHelper, there will be a keyword argument that allows you to enable or disable this feature.

The question is: what should the default value be? Should this feature be enabled by default or disabled by default?

@christopher-dG @fredrikekre - Would love to get your input on this.

**Comment by christopher-dG** [comment]
Yeah I would love this.

**Comment by DilumAluthge** [comment]
> Yeah I would love this.

Sounds good. I'll work on implementing it.

I think that this should be an opt-in feature. So because it won't change the default behavior, this won't need to be a breaking change.

**Comment by tkf** [comment]
FYI here is what I've been using for this https://github.com/tkf/BangBang.jl/blob/master/.github/workflows/pkg-update.yml

> what should the default value be?

Doing this by default (i.e., detect it automatically by checking if Manifest.toml files are checked in) would be great.  I think it's consistent with Manifest.toml files updated by default.
