### ISSUE TITLE
Bug: if you are missing a Julia compat, CompatHelper doesn’t help you 

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/CompatHelper.jl#169]
Current behavior: if you do not have a compat entry for Julia, CompatHelper does not help you,

Desired behavior: if you do not have a compat entry for Julia, CompatHelper makes a PR to add a compat entry for Julia.

**Comment by Octogonapus** [comment]
This should be closed. CompatHelper can add new compat entries now.

**Comment by DilumAluthge** [comment]
CompatHelper can add new entries for packages, but I don't think it adds Julia compat entries.
