### ISSUE TITLE
CompatHelper crashes on unresovable project

### ISSUE THREAD

**Issue by ericphanson** [JuliaRegistries/CompatHelper.jl#179]
The problem is that the unresolvable project isn't the main `Project.toml` of the package, but rather is in a subdirectory, along with a Manifest pointing at the master version of a package (making it instantiate-able). It would be great to be able to use CompatHelper for the main Project.toml, but still have other environments in the repo giving the right branches etc for special situations.

Package with main environment: https://github.com/ericphanson/GuessworkQuantumSideInfo.jl

Failed CompatHelper run: https://github.com/ericphanson/GuessworkQuantumSideInfo.jl/runs/412677111?check_suite_focus=true

Special master-branch-using subenvironment: https://github.com/ericphanson/GuessworkQuantumSideInfo.jl/tree/master/test/high_precision_tests

Sorry if this is a duplicate! Didn't see anything already.

**Comment by ericphanson** [comment]
This problem seemed to go away once I added proper compat, but I think there's still an underlying issue.

**Comment by DilumAluthge** [comment]
We no longer instantiate or update manifest files, so I think this is resolved now.
