### ISSUE TITLE
Tell people not to download Julia in their CompatHelper workflows

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/CompatHelper.jl#185]
Now that we have Julia installed by default in GitHub Actions virtual environments, we need everybody to modify their CompatHelper workflow files to not download Julia.

What is the best approach here?

cc-ing some Actions people: @saschamann @davidanthoff

Also cc-ing @christopher-dg since he did a lot of work making PRs to everyone's repos to do a workflow migration.

Please cc anyone else that can help out.

**Comment by christopher-dG** [comment]
If you decide to go the mass-PR route, you can look up repos to operate on with the search API. I did a test query and got about 1100 results.
From there, fork -> text substitution -> PR  would be pretty straightforward.

**Comment by davidanthoff** [comment]
I think we should really try to get the julia pkg butler more stable and then try to push that out widely. These kind of updates will happen regularly, and with pkg butler it is literally a piece of cake to update _all_ packages that are under its control to for example make this change here.

**Comment by DilumAluthge** [comment]
@davidanthoff Would you be willing to make automated PRs to install pkg butler on everyone's repo?

**Comment by SaschaMann** [comment]
PkgButler does a lot of extra things. While I think it's a great tool and many packages should probably use it, I'm not sure I agree with mass-installing it.

Because it hasn't been mentioned yet: we should remove it from the PkgTemplates CompatHelper files.

**Comment by ericphanson** [comment]
The mass TagBot PRs got some pushback; maybe a less intrusive solution is better, such as the one in @tpapp’s comment here: https://discourse.julialang.org/t/ann-the-tagbot-github-app-is-deprecated-in-favour-of-the-tagbot-github-action/34344/31

**Comment by davidanthoff** [comment]
> PkgButler does a lot of extra things. While I think it's a great tool and many packages should probably use it, I'm not sure I agree with mass-installing it.

We could certainly slim it down more so that it really only keeps stuff up-to-date that is already in a repo, and that the more opinionated stuff is reserved for specific templates. Even if we did that, I think we shouldn't mass-install it, but just advertise it and convince folks to use it. Also, enabling requires certain github permissions that a bot wouldn't have, so I think that wouldn't even be an option. But before we contemplate any of that we would probably have to make it more stable :)

**Comment by DilumAluthge** [comment]
I'll just make a Discourse post asking people to update their CompatHelper workflows.
