### ISSUE TITLE
Move this repo to the JuliaRegistries organization?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/CompatHelper.jl#235]
Would it make sense to move this repo to the JuliaRegistries organization? There, it can live alongside Registrator, TagBot, etc.

cc: @StefanKarpinski

**Comment by StefanKarpinski** [comment]
Yes, seems like a good place to move it to. Do you need any additional permissions to do so?

**Comment by DilumAluthge** [comment]
Nope, it is all set!
