### ISSUE TITLE
Preserve `Project.toml` formatting and/or format long `authors` lists in `Project.toml` nicer

### ISSUE THREAD

**Issue by fingolfin** [JuliaRegistries/CompatHelper.jl#239]
Our package has several authors, and for various reasons I prefer to format them in the `Project.toml` so that each person is on their own line (e.g. it increases visibility of the names when people look at it).

Unfortunately, `CompatHelper` destroys this. Example from https://github.com/oscar-system/Oscar.jl/pull/133:
```
authors = [
  "Claus Fieker <fieker@mathematik.uni-kl.de>",
  "Giovanni De Franceschi <franceschi@mathematik.uni-kl.de>",
  "Johannes Schmitt <schmitt@mathematik.uni-kl.de>",
  "Max Horn <horn@mathematik.uni-kl.de>",
  "William Hart <goodwillhart@googlemail.com>",
  ]
```
is changed to
```
authors = ["Claus Fieker <fieker@mathematik.uni-kl.de>", "Giovanni De Franceschi <franceschi@mathematik.uni-kl.de>", "Johannes Schmitt <schmitt@mathematik.uni-kl.de>", "Max Horn <horn@mathematik.uni-kl.de>", "William Hart <goodwillhart@googlemail.com>"]
```

Usually preserving existing formatting is fiddly (it means one can't use a standard TOML parser), but perhaps at least a way to serialize this field nicer, i.e. if the number of authors exceeds a fixed threshold (say 1 or 2) then the author names are listed each on a separate line?

**Comment by StefanKarpinski** [comment]
Note that @KristofferC is working on a rewritten TOML parser/writer and this could perhaps be improved.

**Comment by DilumAluthge** [comment]
I think this needs to be fixed upstream in the TOML stdlib.
