### ISSUE TITLE
Feature request: support packages hosted on GitLab

### ISSUE THREAD

**Issue by tpapp** [JuliaRegistries/CompatHelper.jl#243]
Is it somehow possible to use CompatHelper for a package hosted on Gitlab? If someone has an example I would appreciate a link.

**Comment by fchorney** [comment]
We are looking to add this functionality and will be working on it in the near future.

**Comment by mattBrzezinski** [comment]
Going to tackle this issue in two-fold;

1) Port this package to use `GitForge.jl` instead of `GitHub.jl`, this will give us the foundation to incorporate usages of GitLab
2) Introduce functionality to work with Gitlab, refactor code, etc.

**Comment by fchorney** [comment]
This is also theoretically "done" in v3 I believe.
