### ISSUE TITLE
Don't make a PR to packages that use an equality specifier

### ISSUE THREAD

**Issue by Octogonapus** [JuliaRegistries/CompatHelper.jl#250]
I have a request based on a PR I just closed this morning:
> This pull request changes the compat entry for the `FFTW` package from `=1.2.2` to `=1.2.2, 1.2`.

We have an equality specifier on `FFTW` because there are bugs in later versions that prevent us from using them; we must use precisely `FFTW = "=1.2.2"`. It doesn't make sense to me why CompatHelper should change the compat entry in this case, since I have explicitly declared that I want one exact version of the package. My request is that CompatHelper does not make a PR changing the compat entry for this package because I used an equality specifier. Does this make sense to anyone else? Am I missing a use case that this was designed for?

**Comment by DilumAluthge** [comment]
Happy to support this feature. We wouldn't make it the default behavior, but we could have a keyword argument that you could set.

(To elaborate, the default behavior of CompatHelper is designed to meet the following goal: make sure that package X is compatible with the latest version of all of its dependencies.)

But yes, we'd be happy to accept a PR to add this feature as an opt-in.
