### ISSUE TITLE
Can you clarify exactly what this package does please?

### ISSUE THREAD

**Issue by cjdoris** [JuliaRegistries/CompatHelper.jl#255]
The README says:
> Whenever one of your package's dependencies releases a new version, CompatHelper opens a pull request on your repository that modifies your `[compat]` entry to reflect the newly released version.

Please can you clarify exactly what changes to `[compat]` you make (perhaps in the README) because it's not totally obvious (to me)?

It's not obvious to me what useful bounds changes this package could automatically make --- if we are following SemVer, if my package has a dependency on some other package at version 1.2, I don't care if that package is updated to version 1.2.1 or 1.3 since I'm already compatible with them all.

Thanks!

**Comment by fredrikekre** [comment]
You are correct, CompatHelper does not update the compat if you are already compatible with the new version. But if one of your dependencies releases v2 for example, then CompatHelper sends you a PR. It is then, of course, up to you to verify if your package actually works with the new version or not.

In a perfect world CompatHelper would rarely have to do any work. However, in practice people think it is fun to make breaking releases that are not actually breaking.

**Comment by cjdoris** [comment]
Thanks for explaining. Can I suggest put that explanation at the top of your README?

**Comment by DilumAluthge** [comment]
I've added the text "breaking releases" to the top of the README.
