### ISSUE TITLE
CompatHelper opens PRs though it opened the same one the day before

### ISSUE THREAD

**Issue by kellertuer** [JuliaRegistries/CompatHelper.jl#261]
While it might be nice to remind package developers to update their compats, on

https://github.com/JuliaManifolds/Manifolds.jl/pull/275

we are waiting for our indirect dependencies (we have ForwardDiff in our `[extra]`s), but CompatHelper opens a new PR every day, see for example

https://github.com/JuliaManifolds/Manifolds.jl/pull/282

Can that somehow be fixed?

**Comment by kellertuer** [comment]
The same also happens, if the old one passes, see https://github.com/JuliaManifolds/Manifolds.jl/pull/280 from yesterday and https://github.com/JuliaManifolds/Manifolds.jl/pull/281 from today (but that one I just resolved to avoid getting another one tomorrow).

**Comment by DilumAluthge** [comment]
Yeah, these duplicated PRs are because you are using a custom personal access token (PAT) for CompatHelper.

CompatHelper does not officially support using a custom PAT.

I've made a PR to fix it here: https://github.com/JuliaManifolds/Manifolds.jl/pull/374
