### ISSUE TITLE
with_tmp_dir atexit hook fails

### ISSUE THREAD

**Issue by fkastner** [JuliaRegistries/CompatHelper.jl#264]
Hi,

I just noticed that the `atexit` hook fails for `with_tmp_dir` because the directory is already gone.
I think the problem is `walkdir` in `prepare_for_deletion` which throws an error by default if it can't `readdir` the directory.
Maybe providing a custom error handler to `walkdir` could fix this?

You can see the error e.g. in [this CompatHelper run](https://github.com/fkastner/NiceNumbers.jl/runs/1801953405?check_suite_focus=true).

**Comment by fkastner** [comment]
bump?

**Comment by DilumAluthge** [comment]
I think #280 should fix all of these issues. Let me know if you still notice any issues after #280 is merged and a new release is registered.
