### ISSUE TITLE
Allow option for enabling updates of `jll`

### ISSUE THREAD

**Issue by vchuravy** [JuliaRegistries/CompatHelper.jl#267]
In Enzyme.jl I would like to bump the compat requirement when a new Enzyme_jll is released cc: @wsmoses

https://github.com/JuliaRegistries/CompatHelper.jl/blob/d7df0f41da8ce0ad9590b8489d266c7e0258f295/src/get_project_deps.jl#L67-L69

**Comment by DilumAluthge** [comment]
We should think about enabling this by default for all JLL packages.

**Comment by DilumAluthge** [comment]
Anyway, let's start by making it opt-in only (#301). That hopefully meets your use case for Enzyme.jl.

Then, in the future, we can think about making it the default behavior. See also https://github.com/JuliaRegistries/RegistryCI.jl/issues/394
