### ISSUE TITLE
CompatHelper keeps suggesting previous versions of 0.x format

### ISSUE THREAD

**Issue by Datseris** [JuliaRegistries/CompatHelper.jl#346]
I keep getting this PR: https://github.com/JuliaDynamics/ChaosTools.jl/pull/195

It suggests that I add a version of a package `0.11` to my compat, when I updated to version `0.12`. The code does not work with `0.11`, and given that there is no major version, the change from `0.11` to `0.12` is breaking. Why is the bot continuing to suggest this change?

**Comment by DilumAluthge** [comment]
Duplicate of #266
