### ISSUE TITLE
CompatHelper v3.0.0 - GitHub action fail with ERROR: Private key is not in the correct format.

### ISSUE THREAD

**Issue by ylvain** [JuliaRegistries/CompatHelper.jl#381]
Hi,
I'm new to both Julia and GitHub actions. So I'll try to describe the issue. I've a few private repo that are Julia package created by PkgTemplate. The only workflow I've got is the default one for CompatHelper. The first step is `julia -e 'using Pkg; Pkg.add("CompatHelper")'`. 

* On some of my repo, this installs v2.1.1 and all is fine. All daily runs install the v2.1.1 including the one of today (about 10 hours ago)
* On some other repo, since about 4 ou 5 days ago, this installs v3.0.0. I do not know why some job resolve to this new major version and some others don't... Anyway, in all cases where the first step install v3.0.0, the second part of the job with the following error.

```julia
[ Info: EnvVar `COMPATHELPER_PRIV` is defined, nonempty, and not `false`
[ Info: This doesn't look like a raw SSH private key. I will assume that it is a Base64-encoded SSH private key. I will now try to Base64-decode it.
ERROR: Private key is not in the correct format. It must be a private key in PEM format. You should use the OpenSSH `ssh-keygen` command to generate the private key. You should pass the `-m PEM` option to ensure that the private key is in PEM format.

Stacktrace:
  [1] decode_ssh_private_key(content::String)
    @ CompatHelper ~/.julia/packages/CompatHelper/6Gctp/src/utilities/ssh.jl:29
  [2] macro expansion
    @ ~/.julia/packages/Mocking/GhDrf/src/mock.jl:29 [inlined]
```

Seems very related to #380 ? 
Or maybe I should change my workflow file as in PR #379 ?
I've no idea what I'm doing, sorry 😄 

The default workflow file I've got is:

```yaml
name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        run: julia -e 'using CompatHelper; CompatHelper.main()'
```

**Comment by samtalki** [comment]
+1, I am experiencing identical behavior using default CompatHelper settings per the documentation.

**Comment by mattBrzezinski** [comment]
I just saw this on the Julia Slack as it was brought up. I'll take a look into this and will be implementing #380. It's a bit tricky to debug here since you cannot safely see what the `DOCUMENTER_KEY` value is without exposing it to everyone. But there definitely is something missing here for using the secret.

Fix should be up within an hour or so, just in some meetings currently. Appreciate the issue being opened up! And thanks for your patience :)
