### ISSUE TITLE
Custom private registries support

### ISSUE THREAD

**Issue by SebastianM-C** [JuliaRegistries/CompatHelper.jl#396]
Hi, thanks for creating this package.
Is there a way to use CompatHelper with private custom registries?
I looked through the code and I see that 
https://github.com/JuliaRegistries/CompatHelper.jl/blob/3d2049f9c305f572117ca90d9fdc6f9db11ea342/src/dependencies.jl#L69-L69
just clones the registries passed as arguments, but the `git_clone` function
https://github.com/JuliaRegistries/CompatHelper.jl/blob/3d2049f9c305f572117ca90d9fdc6f9db11ea342/src/utilities/git.jl#L72-L84
is not passed any private keys.

I think that one easy solution would be to add a pkeys argument to the `main` function that would be a dictionary of registry names => SSH keys.
Another option would be to use the registries in Pkg as suggested in #395

If you'd like I can make a PR to adress this, but I'm not sure how to do tests.

**Comment by DilumAluthge** [comment]
I think https://github.com/JuliaRegistries/CompatHelper.jl/issues/395 might be the best route to go here.
