### ISSUE TITLE
GH Action tests are not triggered by CompatHelper PR 2

### ISSUE THREAD

**Issue by fonsp** [JuliaRegistries/CompatHelper.jl#409]
#387 is still not fixed:

https://github.com/JuliaPluto/PlutoSliderServer.jl/pull/62, with the [workflow file](https://github.com/JuliaPluto/PlutoSliderServer.jl/blob/main/.github/workflows/CompatHelper.yml)

**Comment by fonsp** [comment]
Another example: https://github.com/JuliaPluto/PlutoSliderServer.jl/pull/85

**Comment by DilumAluthge** [comment]
https://github.com/JuliaPluto/PlutoSliderServer.jl/blob/6eb427ff0071273bab23b4c8038639537b63eec4/.github/workflows/CompatHelper.yml#L31

Does your repo have a secret named `DOCUMENTER_KEY`?

**Comment by fonsp** [comment]
Ah I see, thanks!
