### ISSUE TITLE
CompatHelper stopped working on Bokeh.jl

### ISSUE THREAD

**Issue by cjdoris** [JuliaRegistries/CompatHelper.jl#428]
https://github.com/cjdoris/Bokeh.jl/actions/workflows/compathelper.yml

It stopped working about a week ago, and I can't figure out why!

The workflow YAML file is exactly the same as the one CompatHelper suggests to use. The documenter key works fine, inasmuch as the documentation still builds. I tried regenerating the key, but that didn't help.

Could someone take a look please? I'm hoping another set of eyes will see what the issue is. Thanks.

**Comment by musoke** [comment]
This looks like it is resolved?

**Comment by cjdoris** [comment]
Indeed, thanks.
