### ISSUE TITLE
CompatHelper on GHA: Started erroring with pkg_server_registry_url not defined

### ISSUE THREAD

**Issue by kellertuer** [JuliaRegistries/CompatHelper.jl#437]
A few days ago our CompatHelper started erroring with the message that

```
ERROR: LoadError: UndefVarError: pkg_server_registry_url not defined
```

see
https://github.com/JuliaManifolds/Manifolds.jl/runs/8007521423?check_suite_focus=true#step:3:9

**Comment by DilumAluthge** [comment]
It looks like you're using CompatHelper v2. Can you upgrade to CompatHelper v3?

**Comment by kellertuer** [comment]
Ah, interesting, I will try, but I fear that will not run on a PR? I would prefer not to push such a test directly to master.

**Comment by mattBrzezinski** [comment]
> Ah, interesting, I will try, but I fear that will not run on a PR? I would prefer not to push such a test directly to master.

Actions should run updated workflows in a PR.

**Comment by kellertuer** [comment]
Sure, but this is just a scheduled GHA that does not run on push/pull/PR.

**Comment by kellertuer** [comment]
Ah I could manually trigger running the GHA from that branch and it runs fine. So upgrading to version 3 resolved the problem.

**Comment by DilumAluthge** [comment]
See also: https://github.com/JuliaRegistries/General/pull/67188
