### ISSUE TITLE
Feature request: open PRs to update compat entries for weak dependencies (`[weakdeps]`)

### ISSUE THREAD

**Issue by prbzrg** [JuliaRegistries/CompatHelper.jl#452]
the compats for `weakdeps` isn't getting any update.

**Comment by sethaxen** [comment]
Is it possible this is as simple as changing [this line](https://github.com/JuliaRegistries/CompatHelper.jl/blob/e1ce1c425e803c1d4ffe151008439a0e767ed507/src/dependencies.jl#L23-L24) to also look at `weakdeps`?

**Comment by DilumAluthge** [comment]
You probably need to wrap that entire `if` block in a `for` loop that has two iterations. The first iteration will look for `deps`/`compat`, and the second iteration will look for `weakdeps`/`WeakCompat`.

**Comment by DilumAluthge** [comment]
Also, we probably want to have some way of mentioning (in the PR title) that a CompatHelper PR is for a weakdep (as opposed to a regular dep).
