### ISSUE TITLE
We need to start opening PRs to add/update compat entries for stdlibs

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/CompatHelper.jl#456]
See also:
1. https://github.com/JuliaRegistries/RegistryCI.jl/pull/516
2. https://discourse.julialang.org/t/psa-compat-requirements-in-the-general-registry-are-changing/104958?u=dilumaluthge

**Comment by vchuravy** [comment]
We can do this automatically with https://github.com/KristofferC/StdlibRegistryCompatUpdater I can either do a PR per stdlib or one large one.

**Comment by DilumAluthge** [comment]
There are two separate tasks here:
1. In the future, CompatHelper.jl needs to open PRs (to Julia package repos) to add or update `[compat]` entries for stdlibs. (Currently, CompatHelper.jl excludes stdlibs.)
2. We need to make PRs to the registry to go back and retroactively add `[compat]` entries for stdlibs.

The first task will be done in 

For the second task, @vchuravy it would be great if you can do this (with https://github.com/KristofferC/StdlibRegistryCompatUpdater, presumably). I think it might be easier to do a single large PR, but I would also be fine with a PR per stdlib. @KristofferC do you have a preference (single large PR versus one PR per stdlib)?

**Comment by lgoettgens** [comment]
This won't work (at least easily) for some stdlibs. SHA.jl changed from julia 1.7 to 1.8 from being version 1.7 to 0.7.

More critical: Test.jl does not have any version number on julia 1.3 and earlier that can be used in a compat entry.

See https://julialang.slack.com/archives/C67910KEH/p1697546952011759
